apiVersion: apps/v1
kind: Deployment
metadata:
  name: azdevops-agent
  labels:
    app: azdevops-agent
spec:
  replicas: 2
  selector:
    matchLabels:
      app: azdevops-agent
  template:
    metadata:
      labels:
        app: azdevops-agent
    spec:
      containers:
      - name: azdevops-agent
        image: immerslve/azp-agent:latest
        env:
          - name: AZP_URL
            value: "https://dev.azure.com/chris1997/"
          - name: AZP_TOKEN
            valueFrom:
              secretKeyRef:
                name: azdevops 
                key: AZP_TOKEN
          - name: AZP_POOL
            value: "Default"
        resources:
          limits:
            cpu: "10"
            memory: "12Gi"
          requests:
            cpu: "0.5"
            memory: "2Gi"